---
# tasks file for dspace7.postgresql

# Variables
- import_tasks: variables.yml

# Setup/install tasks
- import_tasks: setup.yml

# Initiatlize
- include_tasks: initialize.yml

# Configure
- include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes

# Configure PostgreSQL databases
- include_tasks: databases.yml

# Configure PostgreSQL users
- include_tasks: users.yml

- name: Restart PostgreSQL server
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
