---
- name: Install nvm for user {{ project_dspace_user }}
  shell: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash"
  become: true
  become_user: "{{ project_dspace_user }}"
  args:
    warn: false

- name: Add nvm to bash
  lineinfile:
    dest: "/home/{{ project_dspace_user }}/.bashrc"
    line: source ~/.nvm/nvm.sh
    insertafter: EOF

- name: Install nodejs for user {{ project_dspace_user }}
  shell: source /home/{{ project_dspace_user }}/.bashrc && nvm install v{{ node_version }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ project_dspace_user }}"

- name: Install yarn for user {{ project_dspace_user }}
  shell: source /home/{{ project_dspace_user }}/.bashrc && npm install -g yarn
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ project_dspace_user }}"
