---
- name: Clone dspace-angular repository from GitLab into {{ dspace_angular_home_dir }}
  git:
    repo: "{{ dspace_angular_git_repo }}"
    dest: "{{ dspace_angular_home_dir }}"
    clone: yes
    update: yes
    force: yes
    version: "{{ dspace_angular_git_branch }}"
  become: yes

- name: Chown dspace-angular files to {{ project_dspace_user}} user
  file:
    path: "{{ dspace_angular_home_dir }}"
    owner: "{{ project_dspace_user }}"
    group: "{{ project_dspace_group }}"
    recurse: yes
  become: yes
