---
- name: Set up nodejs repository
  shell: "curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -"
  become: yes
  args:
    warn: false

- name: Install global NodeJS
  yum:
    name: 'nodejs-{{ global_node_version }}'
    state: present
  become: yes

- name: Install PM2 node.js package globally.
  community.general.npm:
    name: pm2
    version: '{{ pm2_version }}'
    global: yes
  become: yes

- name: Install PM2-logrotate
  command: pm2 install pm2-logrotate
  become: yes

- name: Create dspace-angular.json configuration file for PM2
  template:
    src: dspace-angular.json.j2
    dest: '/home/{{ project_dspace_user }}/dspace-angular.json'
  become: yes
  become_user: "{{ project_dspace_user }}"

- name: Install PM2 systemd service
  template:
    src: pm2-dspace-angular.service.j2
    dest: /etc/systemd/system/pm2-dspace-angular.service
    mode: '0755'
    owner: "{{ project_dspace_user }}"
    group: "{{ project_dspace_group }}"
  become: yes

- name: Ensure PM2 service is started and enabled on boot
  service:
    name: pm2-dspace-angular
    enabled: yes
    state: restarted
