---
- name: Set up nodejs repository
  shell: "curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -"
  become: yes
  args:
    warn: false

- name: Install nodejs
  yum:
    name: 'nodejs-{{ node_version }}'
    state: present
  become: yes

- name: Install PM2 node.js package globally.
  community.general.npm:
    name: pm2
    version: '{{ pm2_version }}'
    global: yes
  become: yes

- name: Create ecosystem.config.js configuration file for PM2
  template:
    src: ecosystem.config.js.j2
    dest: '{{ dspace_angular_home_dir }}/ecosystem.config.js'
  become: yes
  become_user: "{{ project_dspace_user }}"

- name: Start dspace-angular app with PM2 and ecosystem.conf.js
  shell: |
    source /home/{{ project_dspace_user }}/.bashrc
    pm2 start ecosystem.config.js
  args:
    chdir: "{{ dspace_angular_home_dir }}"
  become: yes
  become_user: "{{ project_dspace_user }}"

- name: Save dspace-angular app for PM2 in /home/{{ project_dspace_user }}/.pm2/dump.pm2
  shell: |
    source /home/{{ project_dspace_user }}/.bashrc
    pm2 save
  become: yes
  become_user: "{{ project_dspace_user }}"

- name: Install PM2 systemd service
  template:
    src: pm2-dspace.service.j2
    dest: /etc/systemd/system/pm2-dspace.service
    mode: '0755'
    owner: "{{ project_dspace_user }}"
    group: "{{ project_dspace_group }}"
  become: yes

- name: Ensure PM2 service is started and enabled on boot
  service:
    name: pm2-dspace
    enabled: yes
    state: restarted
