---
- name: Ensure Solr conf directories exist
  file:
    path: '{{ solr_home_dir }}/data/{{ item }}/conf'
    state: directory
    owner: '{{ solr_user }}'
    group: '{{ solr_group }}'
    recurse: true
  with_items:
    '{{ solr_cores }}'

- name: Copy default configuration for all cores
  command: 'cp -R {{ solr_install_dir }}/solr/example/files/conf/ {{ solr_home_dir }}/data/{{ item }}/'
  args:
    creates: '{{ solr_home_dir }}/data/{{ item }}/conf/solrconfig.xml'
  with_items: '{{ solr_cores }}'
  register: solr_cores_configuration
  become: yes
  become_user: '{{ solr_user }}'

- name: Create configured cores
  command: '{{ solr_install_dir }}/solr/bin/solr create -c {{ item.1 }}'
  when: "'skipped' not in solr_cores_configuration.results[item.0].stdout"
  with_indexed_items: '{{ solr_cores }}'
  become: yes
  become_user: '{{ solr_user }}'
