---
# Create Solr group if doesn't exist.
- name: Make sure solr group exists
  group:
    name: "{{ solr_group }}"
    state: present

# Create Solr user if doesn't exist.
- name: Make sure solr user exists
  user:
    name: "{{ solr_user }}"
    state: present
    group: "{{ solr_group }}"

- name: Increase open file limit
  blockinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    block: |
      solr    soft    nofile    65000
      solr    hard    nofile    65000

- name: Increase max processes limit
  blockinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    block: |
      solr    soft    nproc    65000
      solr    hard    nproc    65000
