---
- name: Create DSpace 7 database role {{ dspace_db_user }} on postgresql server
  postgresql_user:
    name: '{{ dspace_db_user }}'
    password: '{{ dspace_db_password }}'
    role_attr_flags: NOSUPERUSER
    state: present
  become: yes
  become_user: '{{ postgres_user }}'

- name: Create DSpace 7 database owned by {{ dspace_db_user }}
  postgresql_db:
    name: '{{ dspace_db_name }}'
    encoding: UTF-8
    owner: '{{ dspace_db_user }}'
    template: template0
    state: present
  become: yes
  become_user: '{{ postgres_user }}'

- name: Enable pgcrypto DB Extension
  postgresql_ext:
    name: pgcrypto
    db: '{{ dspace_db_name }}'
  become: yes
  become_user: '{{ postgres_user }}'
