---
- name: Install Shibboleth repository
  copy:
    src: security.shibboleth.repo
    dest: "/etc/yum.repos.d/security:shibboleth.repo"
  become: yes

- name: Install the Shibboleth Service Provider
  yum:
    name: shibboleth.x86_64
    state: present

- name: Enable the shibd service and set to restart
  service:
    name: shibd.service
    enabled: yes
    state: restarted
