---
- name: Install Shibboleth repository
  shell: curl --output /etc/yum.repos.d/security:shibboleth.repo  https://download.opensuse.org/repositories/security:/shibboleth/CentOS_7/security:shibboleth.repo
  become: yes

- name: Install the Shibboleth Service Provider
  yum:
    name: shibboleth.x86_64
    state: present

- name: Enable the shibd service and set to restart
  service:
    name: shibd.service
    enabled: yes
    state: restarted
