---
- name: Increase JAVA memory in Tomcat
  replace:
    path: "/etc/sysconfig/{{ tomcat_daemon }}"
    regexp: '#JAVA_OPTS="-Xminf0.1 -Xmaxf0.3"'
    replace: 'JAVA_OPTS="-Xmx2048M -Xms1024M -Dfile.encoding=UTF-8"'

- name: Update port 8080 connector and add AJP connector on port 8009 for DSpace
  replace:
    path: /etc/tomcat/server.xml
    backup: yes
    regexp: '<Connector port="8080" protocol="HTTP/1.1"[\s\S]*redirectPort="8443" />'
    replace: |-
          <Connector port="8080" protocol="HTTP/1.1"
                     minSpareThreads="25"
                     enableLookups="false"
                     redirectPort="8443"
                     connectionTimeout="20000"
                     disableUploadTimeout="true"
                     URIEncoding="UTF-8" />

          <!-- Define an AJP 1.3 Connector on port 8009 -->
          <Connector port="8009" protocol="AJP/1.3" secretRequired="false" redirectPort="8443" />
